### ISSUE TITLE
casting? and "attempt to call value of type '((void) -> (any*) | nil)'"

### ISSUE THREAD

**Issue by daurnimator** [andremm/typedlua#12]
Trying to run:

``` lua
interface foo
    unpack: (self) -> (number)
end
local t:foo = load("return {n=1; unpack = function(self) return self.n end}", nil, nil, nil)();
print(t:unpack())
```

Gives errors:

```
/dev/stdin:1:61: type error, attempt to call value of type '((void) -> (any*) | nil)'
/dev/stdin:1:53: type error, attempt to assign 'nil' to '{unpack:(self) -> (number)}'
/dev/stdin:1:149: type error, attempt to pass '(void)' to field of input type '(self)'
```

FWIW, I got this while trying to reproduce a different error as a test case.

**Comment by daurnimator** [comment]
> No, there is still not way to require/import other definitions inside .tld files.

Is this still the case? Want me to open a new issue?

**Comment by andremm** [comment]
> Is this still the case? Want me to open a new issue?

Yes, this is still the case and please open an issue for this. Thanks!
