### ISSUE TITLE
type error, depending on where an object is created

### ISSUE THREAD

**Issue by armatys** [andremm/typedlua#16]
I have still a few more issues, which I'm encountering in my small project (https://github.com/armatys/splot-code-gen), but I'm trying to write smaller test cases. The example is similar to the last one (full code here: https://github.com/armatys/tlua-tests). Again, two classes `A` and `B`, and the problematic piece of code:

```
const function B:bfoo(): self
  local a: A = A:new()
  self:bbar()
  -- Calling `local a: A = A:new()` here, would not produce any type error
  return self
end
```
The above results in:
```
b.tl:23:3: type error, attempt to call method 'bbar' of type 'nil'
```

I hope I don't sound as complaining too much ;) Let me know if I can be of any help.

**Comment by andremm** [comment]
Sorry for the delay. I just pushed a quick fix for this. Can you please check if it works? Thanks!

**Comment by armatys** [comment]
Thanks, it's fixed now.
I've found however another one:
```
const function B:bfoo(a: A): self
  a.afoo(a) -- This works
  a:afoo() -- but this not
  return self
end
```
as I'm getting `b.tl:23:3: type error, attempt to index 'A' with 'afoo'`

**Comment by armatys** [comment]
Yep, works now!

**Comment by armatys** [comment]
I've found just another one (full code here: https://github.com/armatys/tlua-tests/blob/653349789b7a76bf4caae72bb21f194f40c2bb22/a.tl), but the main issue:

```
function A:abar(obj: SubA)
  self:arun(obj.subaname) -- Does not compile cleanly.

  -- This works:
  local s = obj.subaname
  self:arun(s)

  -- This also works:
  self.arun(self, obj.subaname)
end
```

The error: `a.tl:38:3: type error, attempt to call method 'arun' of type 'nil'`
