### ISSUE TITLE
can only be run from own directory?

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#18]
Ubuntu 14.04 LTS 32bit intel
here's what i did:
0) installed lua5.2 via syanptic
1) checked out typedlua
2) checked out https://github.com/lua/lpeg.git
3) managed to fiddle with lua includes enough to get lpeg building
4) built tlc
5) when i cd into the tlc directory then ./tlc works. BUT if i'm not in that directory then when i try to call it with the relative path e.g. ../typedlua/tlc i get errors:

x@x:~/Dev$ typedlua/tlc
lua: typedlua/tlc:3: module 'typedlua.tlast' not found:
	no field package.preload['typedlua.tlast']
	no file '/usr/local/share/lua/5.2/typedlua/tlast.lua'
	no file '/usr/local/share/lua/5.2/typedlua/tlast/init.lua'
	no file '/usr/local/lib/lua/5.2/typedlua/tlast.lua'
	no file '/usr/local/lib/lua/5.2/typedlua/tlast/init.lua'
	no file '/usr/share/lua/5.2/typedlua/tlast.lua'
	no file '/usr/share/lua/5.2/typedlua/tlast/init.lua'
	no file './typedlua/tlast.lua'
	no file '/usr/local/lib/lua/5.2/typedlua/tlast.so'
	no file '/usr/lib/i386-linux-gnu/lua/5.2/typedlua/tlast.so'
	no file '/usr/lib/lua/5.2/typedlua/tlast.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './typedlua/tlast.so'
	no file '/usr/local/lib/lua/5.2/typedlua.so'
	no file '/usr/lib/i386-linux-gnu/lua/5.2/typedlua.so'
	no file '/usr/lib/lua/5.2/typedlua.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './typedlua.so'
stack traceback:
	[C]: in function 'require'
	typedlua/tlc:3: in main chunk
	[C]: in ?
x@x:~/Dev$

**Comment by andremm** [comment]
Hi, I just pushed two commits that should fix this issue. Can you please pull and check if it works. Thanks!

**Comment by raould** [comment]
holy cow, thank you. will try it!

(i had locally hacked up a symlink and some edited some paths in the lua files and managed to get it working here but it is a horrible, horrible hack so i never mentioned it.)

**Comment by raould** [comment]
Looks to me that there is some path dependency? 

MacBook Pro / OS X 10.9.5

typedlua 509 $ git pull
remote: Counting objects: 65, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 65 (delta 27), reused 28 (delta 11)
Unpacking objects: 100% (65/65), done.
From https://github.com/andremm/typedlua
   7831181..28d1c9b  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 28d1c9b10c9ab824da44c5a13ed9d1b7c3b9c7a1.
typedlua 510 $ ./tlc
tlc: no input file given
usage: tlc [options] [filename]
Available options are:
-d	dump the AST
-h	print this help
-o name	output to file 'name' (default is 'tlc.lua')
-p	print the AST
-s	strict mode on
-v	print current version
-w	consistent-subtyping warnings on
typedlua 511 $ cd ../
Dev 512 $ typedlua/tlc
lua: typedlua/tlc:3: module 'typedlua.tlast' not found:
	no field package.preload['typedlua.tlast']
	no file '/usr/local/share/lua/5.2/typedlua/tlast.lua'
	no file '/usr/local/share/lua/5.2/typedlua/tlast/init.lua'
	no file '/usr/local/lib/lua/5.2/typedlua/tlast.lua'
	no file '/usr/local/lib/lua/5.2/typedlua/tlast/init.lua'
	no file './typedlua/tlast.lua'
	no file '/usr/local/lib/lua/5.2/typedlua/tlast.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './typedlua/tlast.so'
	no file '/usr/local/lib/lua/5.2/typedlua.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './typedlua.so'
stack traceback:
	[C]: in function 'require'
	typedlua/tlc:3: in main chunk
	[C]: in ?

**Comment by andremm** [comment]
Where did you install the directory `typedlua`?

For instance, you should copy the directory `typedlua` to `/usr/local/share/lua/5.2/`,
so `/usr/local/share/lua/5.2/typedlua` has the same content as the directory `typedlua`
from github.

**Comment by raould** [comment]
I didn't think it had to be anywhere specific, I put it in my own local development directory. :-)

**Comment by andremm** [comment]
No. Like any other Lua module, the Lua files should be installed in one the options listed in `package.path`.
See `http://www.lua.org/work/doc/manual.html#pdf-package.path`.
It works from its own directory because `./?.lua` is one of the options.

**Comment by raould** [comment]
Thanks. Probably worth mentioning explicitly in the README for dummies like me :-)

**Comment by andremm** [comment]
You can also use luarocks to install it.

1) `luarocks pack typedlua-scm-1.rockspec`
2) `luarocks install typedlua-scm-1.src.rock
