### ISSUE TITLE
Emitting type information

### ISSUE THREAD

**Issue by jacobdufault** [andremm/typedlua#21]
Is it possible to dump typing information from a lua file, ie, `./tlc --dump-types myfile.lua` creates a tld file that also includes type information on locals? I'd like to investigate writing an auto-completion library that leverages typedlua's type analysis.

**Comment by andremm** [comment]
Yes. It is possible. You just needs traverse the AST printing out the typing information that is associated to the locals and globals that are being declared.

**Comment by mascarenhas** [comment]
Let me expand on Andre's answer: .tld files are just for the public interface of a module, so there is no way to generate a .tld file with the local declarations. Anyway, for good autocomplete you want full type information for every expression, not just identifiers, and this is what the AST after running tlchecker.typecheck on it does: every expression AST node is tagged with a `type` field that holds that expression's type.

I have changed the `-d` option of `tlc` to take a file and dump the typechecked AST to this file, in a `loadfile`-friendly format that you can load and then traverse, or convert to something else like JSON. Hope it helps!
