### ISSUE TITLE
Searching for package fails

### ISSUE THREAD

**Issue by armatys** [andremm/typedlua#22]
When writing something like `require 'mod.x'` tlc fails to find a proper module, even if the file `mod/x.tl` is present (though if a file `mod/x.lua` is already present, no error is raised).

In file `tlchecker.lua` I found a function `searchpath` where I think it could help to replace all the dots in module name, into path delimiters, e.g. `name = string.gsub(name, '%.', '/')`? As I think the the function `package.searchpath` takes care of it, but it's not available on Lua 5.1.

**Comment by andremm** [comment]
Sorry. Since I'm using Lua 5.3 I missed this. I used your suggestion to fix the problem. Can you please check if it works? Thanks!

**Comment by armatys** [comment]
Confirmed, it works now.
