### ISSUE TITLE
General trouble with fn's with option arguments?

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#29]
Please see https://github.com/raould/typedlua/tree/master/QUESTIONS/4 where I am trying to use 
table.insert( t, elem )
rather than
table.insert( t, #t, elem )
But I do not know how to make that pass through tlc unfortunately.

**Comment by andremm** [comment]
You need `#t + 1` while calling `table.insert` because this is an overloaded function, but Typed Lua is set to handle the case that you give the position where the element should be inserted.
