### ISSUE TITLE
confused about 5.1 and 5.2

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#30]
I don't really understand what has happened on my machine, but I'm on Ubuntu 14.04 LTS 32bit Intel, and have both lua 5.1 & 5.2 installed. It looks like when I used luarocks to install typedlua, it decided to only aim for 5.1 since the /usr/local/bin/tlc shell script only has 5.1 directories in the path.

If you (or anybody who understands it) has a chance to coment / document how typedlua is/can be set up to target 5.1, 5.2, 5.3, luajit, etc., that would be very nice.

**Comment by andremm** [comment]
Typed Lua compiler runs according to the Lua version you use to run it. The compiler supports Lua 5.1, 5.2, and 5.3, but still does not support LuaJIT.

**Comment by raould** [comment]
Ah, so whatever I get for "which lua" on my computer will then be used by tlc to go into the relevant compatibility mode. Ok. Thanks.
