### ISSUE TITLE
confused about libraries

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#31]
I do not claim that this is something wrong with tlc, but I am confused & wonder if anybody has clues/ideas about what might be happening. 

if I have 2 files, foo.lua & foo.tl which are the same, containing only:
print(require "cjson")

$ /usr/bin/lua5.1 foo.lua
table: 0x8375a30

$ /usr/bin/lua5.2 foo.lua
table: 0x9246a40

$ tlc foo.tl
/usr/bin/lua: error loading module 'cjson' from file '/usr/lib/i386-linux-gnu/lua/5.1/cjson.so':
    /usr/lib/i386-linux-gnu/lua/5.1/cjson.so: undefined symbol: lua_pcall
stack traceback:
    [C]: in ?
    [C]: in function 'require'
    /usr/local/share/lua/5.1/typedlua/tlchecker.lua:236: in function 'check_require'
    /usr/local/share/lua/5.1/typedlua/tlchecker.lua:789: in function 'check_call'
    /usr/local/share/lua/5.1/typedlua/tlchecker.lua:1441: in function 'check_exp'
    /usr/local/share/lua/5.1/typedlua/tlchecker.lua:560: in function 'check_explist'
    /usr/local/share/lua/5.1/typedlua/tlchecker.lua:763: in function </usr/local/share/lua/5.1/typedlua/tlchecker.lua:756>
    (...tail calls...)
    /usr/local/share/lua/5.1/typedlua/tlchecker.lua:1550: in function 'typecheck'
    /usr/local/lib/luarocks/rocks/typedlua/scm-1/bin/tlc:123: in main chunk
    [C]: in ?

**Comment by andremm** [comment]
I did the same test here I did not have any issue. It looks like that may be something wrong with you cjson installation.

**Comment by raould** [comment]
Thanks, I think I manged somehow to un and re install enough times that somehow it is working again. (!)
