### ISSUE TITLE
OO new() signature

### ISSUE THREAD

**Issue by raould** [andremm/typedlua#36]
When I tried to make a small example of it, I couldn't repro it. The general jist is that I'm trying to make a Class basically, like how the Shape interface is used to make a Class of sorts. But I get an error about the new() function.
e.g.
player.tl:25:26: type error, return type '(self, nil*)' does not match '(self)'
vs.
interace Player { const new:(number, any, any) => (self) }
const function Player:new(size:number, drawer:any, worlddb:any) : self -- this is line 25 per error above.
end

**Comment by raould** [comment]
So I have to have
 const function Player:new(size:number, drawer:any, worlddb:any) -- : self -- taken off return value
which is weird since it no longer feels like it matches the interface's signature for new:().

But if I do that, then it compiles.
BUT then when I try to use that new from another file I get e.g.
  local player = PlayerClass:new(drawer, constants)
  gameLoop.tl:10:19: type error, attempt to index '(void)' with 'new'

**Comment by raould** [comment]
(This is another case where it would be great to have an example in the unit tests showing Class A with member field of type Class B and then Class A newing a value for the field.)

**Comment by raould** [comment]
https://github.com/raould/typedlua/tree/master/QUESTIONS/9

(a) I do not understand the naming relationships. There's the name of the interface in the file that defines it. When I require that in another file, I do not know where/when I have to use the exact same name.

(b) I'm getting player.tl:14:15: type error, attempt to index '(void)' with 'new' and haven't figured out what the difference is between my code & things like the Shape/Circle example. I assume it might be something textually different, but haven't been able to find & understand the key difference.

**Comment by andremm** [comment]
For now, the interface and the local variable that defines the class are distinct. But I'm thinking to adapt the code so you do not need to declare the interface. I mean, it will use the inferred type of the local variable to export the alias the interface is exporting.

**Comment by raould** [comment]
Whatever you choose has risks of course; if things are not constrained then it can be confusing to learn, whereas if things are constrained then somebody will complain that they can't do things their own way :-) :-) so overall I guess it might be better to make things be un-constrained? But then it is good to try to comment on or look out for ways in which newbies can get easily lost / confused about what does / not matter about things like naming-of-the-same-thing-across-files etc.
