### ISSUE TITLE
Syntax errors exit with error()

### ISSUE THREAD

**Issue by hishamhm** [andremm/typedlua#46]
Syntax errors cause tlc to intentionally error() out, and this dumps a stack traceback to the output — for a second I thought that tlc had crashed. Since these are part of normal operation, failures of these kind should probably be caught and output as normal errors.

**Comment by andremm** [comment]
Thanks for the report. I just pushed a commit that should fix it now. Can you please pull it and test it?

**Comment by hishamhm** [comment]
Fix confirmed, thank you!!
