### ISSUE TITLE
Problem in "if" inference: nested type() specializations

### ISSUE THREAD

**Issue by hishamhm** [andremm/typedlua#47]
```lua
-- bug47mod.tld
userdata U
end
foo: () -> (U, nil) | (nil, string)
```

```lua
-- bug47.tl
local bug47mod = require("bug47mod")
local function main()
   local maybe_u, rerr = bug47mod.foo()
   if type(maybe_u) == "nil" then
      if type(rerr) == "string" then
         error("error - "..rerr, nil)
      end
      return
   end
   local u = maybe_u
end
main()
```

Running with `tlc -s bug47.tl` I get no errors. Running with `tlc bug47.tl` I get a crash:

```
/Programs/Lua/5.3.0/bin/lua: ...am/luarocks/prefix-5.3/share/lua/5.3/typedlua/tltype.lua:353: attempt to index a nil value (local 't')
stack traceback:
	...am/luarocks/prefix-5.3/share/lua/5.3/typedlua/tltype.lua:353: in function 'typedlua.tltype.isTuple'
	...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1207: in function <...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1126>
	(...tail calls...)
	...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1511: in upvalue 'check_block'
	...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1203: in function <...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1126>
	(...tail calls...)
	...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1511: in upvalue 'check_block'
	...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:975: in function <...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:949>
	(...tail calls...)
	...luarocks/prefix-5.3/share/lua/5.3/typedlua/tlchecker.lua:1566: in function 'typedlua.tlchecker.typecheck'
	...prefix-5.3/lib/luarocks/rocks-5.3/typedlua/scm-1/bin/tlc:123: in main chunk
	[C]: in ?
```

**Comment by hishamhm** [comment]
After investigating, I concluded that the problem with #47 is that the code that implements the `type(foo) == "bar"` inference assumes that only one level of inference is taking place. The testcase in #47 fails because there are two nested `if type(foo) == "bar"` tests and the second one produces a TUnionlist with zero array elements, causing filter to become nil and breaking the code below.

If I'm understanding correctly, the `l[name].filter` should be an array, `l[name].filters`, to store all filtered items and restore them one at a time.

I don't know if `.bkp` should become `.bkps` too — I didn't understand that part completely yet.

**Comment by andremm** [comment]
As I mentioned in #52 , these part of the code that deal with filters needs a serious refactoring/rewriting to match the current design.

**Comment by mascarenhas** [comment]
I am doing a major refactoring of filters on the branch newfilters, currently it is missing filtering on projection types (this will need a major refactoring of how these are working right now). Once it is done it should remove this issue, plus add a whole lot more flexibility to filters: combining filters with boolean expressions (`and`, `or`, `not`), cascading filters on branches of `if`, filtering on `while`, reverting to previous versions of a filtered type on assignment, filtering the right side of `and` or `or` by what is on the left side (to make things such as `t and t.foo` work). It will also put in the groundwork to make real overloaded functions possible.

**Comment by hishamhm** [comment]
@mascarenhas Awesome! :D

**Comment by Veltas** [comment]
While we're on the subject... can we have `error` and `assert` act as filters?

e.g. below `assert(f)` we can assume `f` is non-nil?

Sometimes this would be a lot more convenient than the other methods.

**Comment by mascarenhas** [comment]
The new system is more modular, so adding a filter on `assert` is useful (not just for `assert(x)` but for something like `assert(type(x) == "string")`. This should be specially useful to filter something coming from the dynamic side with type `any`.
