### ISSUE TITLE
Problem with table.concat

### ISSUE THREAD

**Issue by hishamhm** [andremm/typedlua#49]
Test case:
```lua
-- concat.tl
local x: {string} = {"hello", "world"}
local c = table.concat(x, "", 1, 2)
print(c)
```
Running `tlc concat.tl` I get:
```
concat.tl:4:11: type error, attempt to pass '({integer:(string | nil)}, , 1, 2, nil*)' to field 'concat' of input type '({integer:(string | number | nil)}, (string | nil), (integer | nil), (integer | nil), value*)'
```

If I edit `typedlua/lsl53/table.tld` changing `concat` from:
```lua
concat : ({string|number}, string?, integer?, integer?) -> (string)
```
to:
```lua
concat : ({any}, string?, integer?, integer?) -> (string)
```
Then it types with no errors.

**Comment by andremm** [comment]
The problem with
```lua
concat : ({any}, string?, integer?, integer?) -> (string)
```
is that it will let thinks like below pass the type checker, but that will fail during run-time:
```lua
local x: {boolean} = {true, false}
local c = table.concat(x, "", 1, 2)
print(c)
```
I believe a better type for `table.concat` in Lua 5.3 is
```lua
concat : ({string}|{number}|{integer}|{string|number}|{string|integer}, string?, integer?, integer?) -> (string)
```
In fact, #14 solved this in Lua 5.1 and 5.2. But, for some reason, I forgot to use this approach in Lua 5.3. 
Maybe Typed Lua could be even more restrictive and allow only
```lua
concat : ({string}, string?, integer?, integer?) -> (string)
```
What do you think?

**Comment by hishamhm** [comment]
> [allow only {string}] What do you think?

I think being more restrictive than the standard API is a problem, because people (me included) would go by what the reference manual says. (If _I_ could change the _behavior_ of `table.concat`, then I'd make it accept `{any}` and would make the function support everything that tostring() does :-) , but given the existing behavior, I think `{string}` only is too restrictive)

> I believe a better type for table.concat in Lua 5.3 is...

Yes, I think it is, if an integer is-a number. (If not then we'd have to add even more cases.)

I've been thinking about this a little, and what I've come to think is that apparently in this case we'd like to have a variance rule, because, "for concat, {string} _is_ a suitable replacement for {string|number|integer}".

If I understand correctly, there's no covariance or contravariance for table arguments, right? Because of this:

```lua
-- example showing table types must be invariant
function addstuff(t: {string|number})
   if t[1] then
      assert(type(t[1]) == "string" or type(t[1]) == "number") -- breaks if contravariant
   end
   -- break if covariant:
   t[#t+1] = "hello"
   t[#t+1] = 42
   -- ...or the other way around because I always get these two names mixed up :)
end
x:{string|number} = {} -- only this type works
add_stuff(x)
```

If x is {string}, or if x is {string|number|boolean), `add_stuff(x)` must fail.

What I'm going to propose here (haha, I sound like people from lua-l that keep asking for new features in Lua, you better start to get used to that ;) ), as a future feature perhaps, would be the following: if a table is marked with the const identifier, then the proper variance rule applies. If you're not adding anything to a table, then the received table should be able to accept a smaller type with no problems. The type for table.concat would then be:

```lua
concat : (const {string|number|integer}, string?, integer?, integer?) -> (string)
```

Of course, once you mark tables as const then the implementation should flag errors when it is assigned, and it becomes a matter of time until you want to support const everywhere (which, since the language already has const functions, I think is an inevitable(?) direction, post 0.1). 

But since/while we don't have that, then the type should be really, as you said,

```
concat : ({string}|{number}|{integer}|{string|number}|{string|integer}, string?, integer?, integer?) -> (string)
```

**Comment by andremm** [comment]
>I think being more restrictive than the standard API is a problem...

That's interesting. I thought that being more restrictive in this case wouldn't be really a problem, because `table.concat` is the only place that Typed Lua "allows" coercions between strings and numbers. Anywhere else they are off in Typed Lua.

>Yes, I think it is, if an integer is-a number. (If not then we'd have to add even more cases.)...

An integer is a number, but you are right: variance in tables is really a concern, and table arguments are invariant. This mens that we cannot do
```lua
local x:{string:integer} = { foo = 1, bar = 2 }
local y:{string:number} = x  --> type error
```
due to invariance, that is,  `integer <: number`, but `number </: integer`.

>What I'm going to propose here...

That's cool! :) But I have to admit that `const` still needs improvements in the implementation to match its design. The idea behind `const` actually is to allow covariance between table types. For now, the design of `const` is limited to records only, but following your idea we could allow them in maps and arrays too. In this case, we could write the type of `table.concat` as follows
```lua
concat : ({const integer:string|number}, string?, integer?, integer?) -> (string)
```

I'm really not sure if we need `const` outside tables, because we have literal types that can be used to type constants. For instance,
```lua
local version:"0.1" = "0.1"
version = "0.2" --> type error
```
fails to compile because we cannot change the type of `version`.

Anyway, I will think about it. For now, I used the type that I mentioned in the previous comment:
```lua
concat : ({string}|{number}|{integer}|{string|number}|{string|integer}, string?, integer?, integer?) -> (string)
```

**Comment by hishamhm** [comment]
I know it's a matter of taste, but...

```lua
local version:"0.1" = "0.1"
```

..._looks_ really awkward to me :) (even though the theory behind it is elegant!). 

Having said that, I like that you wrote `{const integer:string|number}` instead of `const {string|number}` as I did before, because that made me realize that, in a sense, constness is not a property of the _value_ (hence, it does not belong as a first-class property of types, which refer to values). Constness is a property of _"slots"_ where you store values: local variables, table keys.

Once we can understand it as a property of the behavior of the slot, then it might not be too strange to say that constness not only affects the variance for tables, but also the local inference rules, so that 

```lua
const version = "0.1"
```

implies type `"0.1"` for `version`.

(The remaining kind of slot would be global variables, but those can't really be const because one cannot enforce constness across modules, due to interoperability with untyped Lua — an excellent excuse for not supporting user-defined global constants :) ).

------

> Anyway, I will think about it. For now, I used the type that I mentioned in the previous comment:

Thanks!

**Comment by andremm** [comment]
> Constness is a property of "slots" where you store values: local variables, table keys.

Exactly! :)

Actually, I'm considering to include in future versions
```lua
local version = const "0.1"
```
instead of
```lua
local const version = "0.1"
```
The reason is because it is a bit easier to the implementation rules of the inference rules. This means that a `const` expression always gives the exact type to unannotated variables, but an expression that does not have the `const` annotation gives the more general type to unannotated variables.
More precisely,
```lua
local msg = const "hello"
```
declares `msg` with type `"hello"`, but
```lua
local msg = "hello"
```
declares `msg` with type `string`.
What do you think about it?

**Comment by hishamhm** [comment]
Given that constness is a property of the slot, I think it would make more sense if the annotation goes with the variable qualifier (either alongside or instead of `local`), and not with the value. I can see how it is more work, but if the variable is annotated as const (and not the value), one can later produce better error messages.

```
const x = "1.0"
x = "2.0"
```

would then give `cannot assign to const variable x` instead of the more cryptic `type error, cannot match type 'string' with type '"1.0"'`. Anyway, something to think about!

**Comment by andremm** [comment]
> Anyway, something to think about!

Sure... plans for future versions. :)
