### ISSUE TITLE
Problem in "if" inference: unions without nil

### ISSUE THREAD

**Issue by hishamhm** [andremm/typedlua#52]
I was reading the code to investigate #47, and while reading the code of `check_if` I noticed that the implementation has problems (I'm also updating #47).

The code in the `if exp.tag == "Id"` section assumes that one of the elements of the union has the `nil` type. I wrote a test case to see if I was understanding the code correctly, and got a confirmation:

```lua
-- non_nil_union.tl
function x() : (integer, boolean)|(string, integer)
   if 0 > 1 then
      return 1, true
   else
      return "wat", 9
   end
end

local foo, bar = x()
if foo then -- *
   local bla = foo .. " world"
end -- *
```
If you comment lines marked with *, you get the correct error:
```
non_nil_union.tl:12:16: type error, attempt to concatenate a '(integer | string)'
```
but if you simply check that foo is non-nil, the inference engine is incorrectly specializing its type to integer:
```
non_nil_union.tl:12:16: type error, attempt to concatenate a 'integer'
```

I think the fix is simple. We need to test if get_index returned something and if it didn't, no filtering happens. But I'd like your confirmation before I submit a pull request.

**Comment by andremm** [comment]
That's true. I'm sorry for that.

**Comment by hishamhm** [comment]
nah, don't worry! I'm having fun and I'm impressed that the code is relatively easy to follow, given that it does complicated stuff!!

**Comment by andremm** [comment]
Thanks, but the code is a bit messy yet. I need to do a serious refactoring to improve some stuff to match the design. That's the reason you are founding some issues with unions and object-oriented programming, as these are the parts that changed in the design and still need improvements in the implementation. Anyway, thanks for all the help!

**Comment by mascarenhas** [comment]
I reopened this because the new filter/projection system now fixes it. Closing it again. :-)
