### ISSUE TITLE
node.l and node.c

### ISSUE THREAD

**Issue by larme** [andremm/typedlua#60]
Hi Andre,

I'm using tlcode.lua to generate lua codes for my own little language. I build the metalua ast manually and use tlcode.generate to generate lua codes from the ast. 

It used to work perfectly but commit 1ea28deb09a20f99704b29ba0c1290fb7ac6a40c broke the codes. This commit requires every node has a .l and .c fields. I tried to update my codes to work with updated tlcode.lua but because my language doesn't store source code position meta data in current stage I haven't succeed yet.

I wonder if we can ignore .l and .c (and maybe .pos) fields in tlcode.lua, or if not, what should I put into these fields? Thanks.

**Comment by andremm** [comment]
Hi Zhao, that's great to know that you are using my code generator.

I'm sorry that we found issues. The reason we made that change is to make it easier to debug Lua code that is generated from Typed Lua code.

Anyway, I just pushed a commit that should make the field `.l` optional for code generation. This means that from now on we should be able to ignore fields `.l`, `.c` and `.pos`. Can you please pull it and check?

Thanks for the report!

**Comment by larme** [comment]
Hi Andre,

Thanks for your quick response. Now my compiler works again, though all indent spaces are lost.

I read the source code of tlcode.lua and it seems that now tlcode will try to generate lua codes that has the same line number as the typed lua codes. If in my compiler I provide `.l` and `.c` fields, will tlcode generate lua codes that has the same lin number as the source language (a lispy language) codes?

regards,
Zhao Shenyang

**Comment by andremm** [comment]
> If in my compiler I provide .l and .c fields, will tlcode generate lua codes that has the same lin number as the source language (a lispy language) codes?

You need only `.l`, because the generator only needs the information about line number to sync source code with generated code.

Can you please test and let me know the results?

I'm sorry for the late response.
