### ISSUE TITLE
require cycles not handled correctly

### ISSUE THREAD

**Issue by kevinclancy** [andremm/typedlua#71]
This example, involving three files, causes a hang when running tlc on testfile1.tl:

tltestfile1.tl
```
require("testfile2")
```

tltestfile2.tl
```
require("testfile3")
```

testfile3.tl
```
require("testfile2")
```

This happens because env.parent contains the file name of the module that was passed as a command-line argument to tlc. Instead, env.parent should be a structure which tracks the names of all modules in the current chain of requires.

**Comment by andremm** [comment]
This issue is similar to issues #44 and #51 and it should be fixed now.
