### ISSUE TITLE
Use assert/error to filter

### ISSUE THREAD

**Issue by Veltas** [andremm/typedlua#96]
I mentioned this previously in a comment in #47 (may as well make an issue page for it).

Can we have `assert` act as a filter?

E.g. below `assert(f)` we can assume `f` is non-nil, below `assert(type(f) == "string")` we can assume `f` is a string, etc.

Sometimes this is neater than moving all dependant code into `if` blocks (this alternative lets us write less indented code). Also this would make a lot of existing Lua code closer to being valid Typed Lua.

Additionally, I suppose filters should also be made from considering sink points of a function, including `error` and `return` (if it does not already do this), e.g.:

```lua
local function double_number(x: number?)
  if not x then
    error("Not giving p1 to double_number is deprecated")
  end
  return 2 * x -- x is filtered to number
end
```

**Comment by mascarenhas** [comment]
Now I get what you meant by filtering on 'error'. We already were tracking returns, so adding this was easy, check the current HEAD, which also adds filtering on assert.

**Comment by mascarenhas** [comment]
The initial implementation was buggy, but should be fixed now.
