### ISSUE TITLE
or filter has broken

### ISSUE THREAD

**Issue by Veltas** [andremm/typedlua#98]
Since patches in the last hour or so, the `or` filter has broken:

```lua
local i: integer? = 3
print(1 + i or 0)
```
Error:
```
type error, attempt to perform arithmetic on a 'integer?'
```

**Comment by mascarenhas** [comment]
This is because `or` has lower precedence than `+`:

    Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
    > 1 + i or 0
    stdin:1: attempt to perform arithmetic on a nil value (global 'i')
    stack traceback:
            stdin:1: in main chunk
            [C]: in ?
    >

Put parenthesis around `i or 0` and it works.
